### ISSUE TITLE
Error message: cannot find t1.shareable.

### ISSUE THREAD

**Issue by MuppetGate** [mariodavid/cuba-component-user-inbox#10]
Hi there. Every time I try to access the user inbox, I get a message saying that t1.shareable does not exist.

I think it should be a field on the ddcii_message table, but it doesn't appear to be there.

**Comment by mariodavid** [comment]
hi,

which RDBMS do you use? Currently officially HSQLDB is supported. For this I added the corresponding update script:

https://github.com/mariodavid/cuba-component-user-inbox/blob/master/modules/core/db/update/hsql/18/180520-2-add-shareable-column-to-message.sql

If you use another RDBMS how did you create the scripts for the app?

**Comment by MuppetGate** [comment]
Hi there.

Didn't create a script; I just added the missing field manually. I was going to just add an update script through Cuba, but I haven't got round to it yet.

**Comment by mariodavid** [comment]
> Didn't create a script

the app component ships the script in 0.3.0 (https://github.com/mariodavid/cuba-component-user-inbox/releases/tag/0.3.0). So if you use HSQLDB, you do not have to do anything.

> I just added the missing field manually

This is very problematic, because CUBA keeps track of the changes in `SYS_CHANGELOG`. If you manually underneath change the reality, then the update mechanism will have a very hard time to understand what is going on.

But this is only true if you are using HSQLDB. For another DBMS the situation might be different, because Studio have to also generate the scripts for the app component as well...

I would suggest to do the following (in case you use HSQLDB):
1. change the name of the database
2. let studio "create database" completely (containing your tables and the app comopnents tables)
3. look at the schema and try to identify the changes compared to your old version

Bye
